FROM ubuntu:18.04
MAINTAINER Ken Raffenetti raffenet@mcs.anl.gov
RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    emacs-nox \
    wget \
    sudo \
    git
USER raffenet
